language: generic
before_install:
  - sudo apt update
  - sudo apt install python3 -y
script:
  python3 build.py
deploy:
  provider: releases
  skip_cleanup: true
  edge: true
  file: build/install.sql
  on:
    repo: llouislu/tsql-diff
    branch: master
  tag_name: "${TRAVIS_COMMIT:0:4}"
  draft: false
  prerelease: false
