language: generic
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install python3 -y
script:
  python3 build.py
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: build/install.sql
  on:
    repo: llouislu/tsql-diff
    branch: master
  tag_name: "v$(date '+%Y%m%d' -u)-${TRAVIS_COMMIT:0:7}"
  draft: false
  prerelease: true
