version: "3.2"
services:

  db:
    container_name: diff-db
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ./docker:/var/opt/mssql
      - ./:/root/data
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: 'PassW0rd123#'
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
